generate_args:
  num_beams: 1
  max_length: 80

only_allowed_tokens: False
batch_size: 2

architecture:
  name: "openai/whisper-large-v2"
  use_pretrained_whisper_encoder: True
  use_pretrained_whisper_decoder: True

data:
  dataset_name: "clotho"
  task: "caption"
  dataset_type: "val"
  data_limit: 4 # (either a number or null)te