hf_training_args:
  do_train: False
  do_eval: True

  per_device_eval_batch_size: 1
  eval_accumulation_steps: 8

  dataloader_num_workers: 16
  dataloader_pin_memory: True
  dataloader_drop_last: False

  report_to: "wandb"
  remove_unused_columns: False # NEVER TOUCH THIS

  metric_for_best_model: "audiocaps/spider"
  greater_is_better: True

  predict_with_generate: True # NEVER TOUCH THIS
  generation_num_beams: 1
  generation_max_length: 80

architecture:
  name: "openai/whisper-large-v2"
  use_pretrained_whisper_encoder: True
  use_pretrained_whisper_decoder: True

data:
  dataset_name: "clotho"
  split_name: "test"
  data_limit: null # (either a number or null)
  log_pred_num: 5
wandb_group: "inference"